# Generated by Django 6.0.3 on 2026-03-25 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_profil_delete_client'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('categorie', models.CharField(choices=[('plombier', 'Plombier'), ('maçonnerie', 'Maçonnerie'), ('electricite', 'Électricité'), ('menuiserie', 'Ménuiserie'), ('carrelage', 'Carrelage'), ('peinture', 'Peinture')], max_length=20)),
                ('budget_min', models.IntegerField()),
                ('budget_max', models.IntegerField()),
                ('localisation', models.CharField(max_length=255)),
                ('statut', models.CharField(choices=[('attente', 'En attente'), ('devis', 'Dévis reçu'), ('encours', 'En cours'), ('termine', 'Terminé')], default='attente', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
