# Generated by Django 6.0.3 on 2026-03-26 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_demande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='budget_max',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='demande',
            name='budget_min',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='demande',
            name='categorie',
            field=models.CharField(blank=True, choices=[('plombier', 'Plombier'), ('maçonnerie', 'Maçonnerie'), ('electricite', 'Électricité'), ('menuiserie', 'Ménuiserie'), ('carrelage', 'Carrelage'), ('peinture', 'Peinture')], max_length=20),
        ),
        migrations.AlterField(
            model_name='demande',
            name='localisation',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='demande',
            name='titre',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
