# Generated by Django 6.0.3 on 2026-03-26 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_demande_budget_max_alter_demande_budget_min_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='categorie',
            field=models.CharField(blank=True, choices=[('Plombier', 'Plombier'), ('Maçonnerie', 'Maçonnerie'), ('Électricité', 'Électricité'), ('Ménuiserie', 'Ménuiserie'), ('Carrelage', 'Carrelage'), ('Peinture', 'Peinture')], max_length=20),
        ),
        migrations.AlterField(
            model_name='demande',
            name='statut',
            field=models.CharField(choices=[('En attente', 'En attente'), ('Dévis reçu', 'Dévis reçu'), ('En cours', 'En cours'), ('Terminé', 'Terminé')], default='attente', max_length=20),
        ),
    ]
