# Generated by Django 6.0.3 on 2026-03-26 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_alter_demande_categorie_alter_demande_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='categorie',
            field=models.CharField(blank=True, choices=[('plombier', 'Plombier'), ('maconnerie', 'Maçonnerie'), ('electricité', 'Électricité'), ('ménuiserie', 'Ménuiserie'), ('carrelage', 'Carrelage'), ('peinture', 'Peinture')], max_length=20),
        ),
    ]
