# Generated by Django 6.0.3 on 2026-03-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_alter_demande_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='budget_max',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='demande',
            name='budget_min',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='demande',
            name='categorie',
            field=models.CharField(choices=[('plombier', 'Plombier'), ('maconnerie', 'Maçonnerie'), ('electricité', 'Électricité'), ('ménuiserie', 'Ménuiserie'), ('ménuiserie', 'Carrelage'), ('peinture', 'Peinture')], max_length=20),
        ),
        migrations.AlterField(
            model_name='demande',
            name='date_creation',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='demande',
            name='localisation',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='demande',
            name='titre',
            field=models.CharField(max_length=255),
        ),
    ]
