# Generated by Django 6.0.3 on 2026-03-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_alter_demande_budget_max_alter_demande_budget_min_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
