# Generated by Django 6.0.3 on 2026-03-26 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_alter_demande_date_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='categorie',
            field=models.CharField(choices=[('Plombier', 'Plombier'), ('Maçonnerie', 'Maçonnerie'), ('Électricité', 'Électricité'), ('Ménuiserie', 'Ménuiserie'), ('Carrelage', 'Carrelage'), ('Peinture', 'Peinture')], max_length=20),
        ),
    ]
