# Generated by Django 6.0.3 on 2026-03-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_alter_demande_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='statut',
            field=models.CharField(choices=[('En attente', 'En attente'), ('Dévis reçu', 'Dévis reçu'), ('En cours', 'En cours'), ('Terminé', 'Terminé')], default='En attente', max_length=20),
        ),
    ]
