# Generated by Django 6.0.3 on 2026-03-26 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_alter_demande_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='categorie',
            field=models.CharField(choices=[('Plomberie', 'Plomberie'), ('Maçonnerie', 'Maçonnerie'), ('Électricité', 'Électricité'), ('Ménuiserie', 'Ménuiserie'), ('Carrelage', 'Carrelage'), ('Peinture', 'Peinture')], max_length=20),
        ),
    ]
