# Generated by Django 6.0.3 on 2026-04-08 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_alter_demande_id_alter_profil_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='is_verified_artisan',
            field=models.BooleanField(default=False),
        ),
    ]
