# Generated by Django 6.0.3 on 2026-04-15 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0014_profil_is_verified_artisan'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='est_fermee',
            field=models.BooleanField(default=False),
        ),
    ]
