# Generated by Django 6.0.3 on 2026-04-20 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Signalement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('contenu', models.TextField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='en_attente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements_envoyes', to=settings.AUTH_USER_MODEL)),
                ('cible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements_recus', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
