# Generated by Django 6.0.3 on 2026-04-20 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrateur', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signalement',
            old_name='acteur',
            new_name='auteur',
        ),
    ]
