# Generated by Django 6.0.3 on 2026-04-20 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrateur', '0002_rename_acteur_signalement_auteur'),
        ('artisans', '0006_artisan_est_valide_alter_artisan_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='signalement',
            name='devis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artisans.devis'),
        ),
        migrations.AddField(
            model_name='signalement',
            name='projet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artisans.projet'),
        ),
    ]
