# Generated by Django 6.0.3 on 2026-04-07 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0013_alter_demande_id_alter_profil_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artisan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('sexe', models.CharField(max_length=10)),
                ('cni', models.CharField(max_length=50)),
                ('nationalite', models.CharField(max_length=50)),
                ('telephone1', models.CharField(max_length=12)),
                ('telephone2', models.CharField(max_length=12)),
                ('email_pro', models.EmailField(max_length=254)),
                ('metier_principal', models.CharField(max_length=100)),
                ('annees_experiences', models.CharField(max_length=50)),
                ('niveau_formation', models.CharField(max_length=100)),
                ('registre_commercial', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
                ('img_cni_recto', models.ImageField(upload_to='cni/')),
                ('img_cni_verso', models.ImageField(upload_to='cni/')),
                ('attestation', models.FileField(upload_to='attestation/')),
                ('photo_profil_pro', models.ImageField(upload_to='profil/')),
                ('ville_principale', models.CharField(max_length=100)),
                ('quartier_intervention', models.TextField()),
                ('rayon', models.IntegerField()),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('disponibilite', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('delai', models.IntegerField()),
                ('message', models.TextField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('accepté', 'Accepté'), ('refusé', 'Refusé')], default='en_attente', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devis', to='clients.demande')),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('termine', 'Terniné'), ('annule', 'Annulé')], default='en_cours', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projets_artisan', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projet_client', to=settings.AUTH_USER_MODEL)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.demande')),
                ('devis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='artisans.devis')),
            ],
        ),
    ]
