# Generated by Django 6.0.3 on 2026-04-08 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artisans', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artisan',
            old_name='img_cni_recto',
            new_name='cni_recto',
        ),
        migrations.RenameField(
            model_name='artisan',
            old_name='img_cni_verso',
            new_name='cni_verso',
        ),
    ]
