# Generated by Django 6.0.3 on 2026-04-09 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artisans', '0002_rename_img_cni_recto_artisan_cni_recto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artisan',
            name='email_pro',
        ),
        migrations.RemoveField(
            model_name='artisan',
            name='nom',
        ),
    ]
