# Generated by Django 6.0.3 on 2026-04-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisans', '0003_remove_artisan_email_pro_remove_artisan_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artisan',
            name='telephone1',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='telephone2',
            field=models.CharField(max_length=15),
        ),
    ]
