# Generated by Django 6.0.3 on 2026-04-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisans', '0004_alter_artisan_telephone1_alter_artisan_telephone2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devis',
            name='delai',
            field=models.IntegerField(default=1),
        ),
    ]
